"""
deductions_guide.py
Complete reference guide for all deductions and exemptions available under
the Old Tax Regime (Income Tax Act 1961) and New Tax Regime (Finance Act 2025 / AY 2026-27+).
"""
from __future__ import annotations

from typing import List, Dict, Any


# ── Salary Exemptions (Section 10) ────────────────────────────────────────────

SALARY_EXEMPTIONS: List[Dict[str, Any]] = [
    {
        "section": "Sec 10(13A)",
        "name": "House Rent Allowance (HRA)",
        "old_regime": True,
        "new_regime": False,
        "limit": "Least of: (i) Actual HRA received, (ii) Rent paid − 10% of basic, (iii) 50% of basic (metro) / 40% of basic (non-metro)",
        "notes": "Requires rent receipts. Not available if you own the house you live in.",
        "category": "Salary Exemption",
    },
    {
        "section": "Sec 10(5)",
        "name": "Leave Travel Allowance (LTA)",
        "old_regime": True,
        "new_regime": False,
        "limit": "Actual fare for domestic travel (economy class / AC 1 tier). 2 journeys in a block of 4 years.",
        "notes": "Block 2022-25 active. Covers self and family (spouse, children, dependent parents/siblings).",
        "category": "Salary Exemption",
    },
    {
        "section": "Sec 10(10)",
        "name": "Gratuity",
        "old_regime": True,
        "new_regime": True,
        "limit": "Up to ₹20,00,000 (govt employees: fully exempt). For others: least of actual gratuity, last salary × 15/26 × years, or ₹20L.",
        "notes": "Payable after 5 years of continuous service.",
        "category": "Salary Exemption",
    },
    {
        "section": "Sec 10(10AA)",
        "name": "Leave Encashment on Retirement",
        "old_regime": True,
        "new_regime": True,
        "limit": "Up to ₹25,00,000 for non-govt employees. Govt employees: fully exempt.",
        "notes": "Only at retirement/resignation. During service, fully taxable.",
        "category": "Salary Exemption",
    },
    {
        "section": "Sec 10(10B)",
        "name": "Retrenchment Compensation",
        "old_regime": True,
        "new_regime": True,
        "limit": "Lower of: 15 days' average pay × years served, or ₹5,00,000.",
        "notes": "Fully exempt for govt employees.",
        "category": "Salary Exemption",
    },
    {
        "section": "Sec 10(10C)",
        "name": "VRS Compensation",
        "old_regime": True,
        "new_regime": True,
        "limit": "Up to ₹5,00,000.",
        "notes": "Available once in a lifetime. Employee must be 40+ years or 10+ years service.",
        "category": "Salary Exemption",
    },
    {
        "section": "Sec 10(14)",
        "name": "Children Education Allowance",
        "old_regime": True,
        "new_regime": False,
        "limit": "₹100 per month per child (max 2 children) = ₹2,400/year",
        "notes": "Separate from 80C tuition fee deduction.",
        "category": "Salary Exemption",
    },
    {
        "section": "Sec 10(14)",
        "name": "Hostel Expenditure Allowance",
        "old_regime": True,
        "new_regime": False,
        "limit": "₹300 per month per child (max 2 children) = ₹7,200/year",
        "notes": "Must be enrolled in school/college hostel.",
        "category": "Salary Exemption",
    },
    {
        "section": "Sec 10(14)",
        "name": "Telephone / Internet Reimbursement",
        "old_regime": True,
        "new_regime": False,
        "limit": "Actual bill amount paid for official use, capped to component in salary slip.",
        "notes": "Bill-based reimbursement. Subject to payroll policy.",
        "category": "Salary Exemption",
    },
    {
        "section": "Sec 10(14)",
        "name": "Uniform Allowance",
        "old_regime": True,
        "new_regime": False,
        "limit": "Actual amount spent on official uniform. Excess taxable.",
        "notes": "Requires bills/receipts. Not applicable for personal clothes.",
        "category": "Salary Exemption",
    },
    {
        "section": "Sec 10(14)",
        "name": "Transport Allowance (Disabled Employees)",
        "old_regime": True,
        "new_regime": True,
        "limit": "₹3,200 per month = ₹38,400/year",
        "notes": "Only for visually impaired employees or those with lower-limb disability.",
        "category": "Salary Exemption",
    },
    {
        "section": "Sec 17(2)",
        "name": "Meal Vouchers / Food Allowance",
        "old_regime": True,
        "new_regime": False,
        "limit": "₹50 per meal × 2 meals/day × working days ≈ ₹26,400/year",
        "notes": "Non-cash food benefit (meal cards / vouchers). Cash reimbursement is taxable.",
        "category": "Salary Exemption",
    },
]

# ── Chapter VI-A Deductions (Old Regime) ─────────────────────────────────────

CHAPTER_VIA_DEDUCTIONS: List[Dict[str, Any]] = [
    {
        "section": "80C",
        "name": "Investments & Savings",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": 150000,
        "limit_text": "₹1,50,000 (aggregate with 80CCC and 80CCD(1))",
        "instruments": [
            "Employee Provident Fund (EPF) — mandatory deduction",
            "Public Provident Fund (PPF)",
            "Equity Linked Savings Scheme (ELSS) — mutual fund, 3-yr lock-in",
            "National Savings Certificate (NSC)",
            "Life Insurance Premium (LIC / any insurer)",
            "5-Year Tax-Saving Bank Fixed Deposit",
            "Senior Citizens Savings Scheme (SCSS)",
            "Sukanya Samriddhi Yojana (SSY) — for girl child",
            "Home Loan Principal Repayment",
            "Tuition Fees (2 children, full-time Indian institution)",
            "National Pension System (NPS) — employee contribution within 80C",
            "Post Office 5-Year Time Deposit",
            "NABARD Rural Bonds",
        ],
        "notes": "Most popular deduction. Maximize to ₹1.5L before considering other sections.",
        "category": "Chapter VI-A",
    },
    {
        "section": "80CCC",
        "name": "Pension Fund (Insurance Company)",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": 150000,
        "limit_text": "₹1,50,000 (included within 80C aggregate limit)",
        "instruments": ["Annuity plan of LIC or any other life insurer"],
        "notes": "Counted within the ₹1.5L 80C aggregate cap.",
        "category": "Chapter VI-A",
    },
    {
        "section": "80CCD(1)",
        "name": "NPS — Employee's Own Contribution",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": 150000,
        "limit_text": "Up to 10% of salary (basic + DA). Included within ₹1.5L 80C cap.",
        "instruments": ["National Pension System (NPS) Tier-I account"],
        "notes": "The 10%-of-salary cap is the binding limit here for employees.",
        "category": "Chapter VI-A",
    },
    {
        "section": "80CCD(1B)",
        "name": "NPS — Additional Employee Contribution",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": 50000,
        "limit_text": "₹50,000 — OVER AND ABOVE the ₹1.5L 80C limit",
        "instruments": ["National Pension System (NPS) Tier-I account"],
        "notes": "One of the best additional deductions. Total NPS benefit can be ₹2L (₹1.5L via 80C + ₹50K here).",
        "category": "Chapter VI-A",
    },
    {
        "section": "80CCD(2)",
        "name": "NPS — Employer's Contribution",
        "old_regime": True,
        "new_regime": True,
        "limit_amount": None,
        "limit_text": "14% of salary for Govt employees; 10% of salary for others. No monetary cap.",
        "instruments": ["Employer's NPS contribution on behalf of employee"],
        "notes": "AVAILABLE IN BOTH REGIMES. Not counted within 80C limit. Excellent tax-free benefit.",
        "category": "Chapter VI-A",
    },
    {
        "section": "80D",
        "name": "Health Insurance Premium",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": 100000,
        "limit_text": "Self/family: ₹25,000 (₹50,000 if self is senior). Parents: ₹25,000 (₹50,000 if senior). Max total: ₹1,00,000.",
        "instruments": [
            "Mediclaim / health insurance premium for self, spouse, children",
            "Health insurance premium for parents",
            "Preventive health check-up (₹5,000 within limit)",
            "CGHS / notified scheme contribution",
        ],
        "notes": "Senior citizen (60+) limits double. Very useful for employees with aging parents.",
        "category": "Chapter VI-A",
    },
    {
        "section": "80DD",
        "name": "Medical Expenditure / Insurance for Disabled Dependent",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": 125000,
        "limit_text": "₹75,000 (normal disability 40%+) or ₹1,25,000 (severe disability 80%+)",
        "instruments": [
            "Insurance premium for disabled dependent",
            "Amount deposited in LIC scheme for maintenance of disabled dependent",
        ],
        "notes": "Fixed deduction — does not depend on actual expenditure. Dependent = spouse, child, parent, sibling.",
        "category": "Chapter VI-A",
    },
    {
        "section": "80DDB",
        "name": "Medical Treatment — Specified Disease",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": 100000,
        "limit_text": "₹40,000 for below 60; ₹1,00,000 for senior citizens (60+)",
        "instruments": [
            "Neurological diseases (dementia, dystonia, Parkinson's, etc.)",
            "Malignant cancers",
            "AIDS",
            "Chronic Renal Failure",
            "Haematological disorders (thalassemia, haemophilia)",
        ],
        "notes": "Deduct any insurance reimbursement received. Requires certificate from a specialist.",
        "category": "Chapter VI-A",
    },
    {
        "section": "80E",
        "name": "Education Loan Interest",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": None,
        "limit_text": "No upper limit. Available for 8 consecutive years from first repayment.",
        "instruments": ["Interest on loan for higher education (self, spouse, children, legal ward)"],
        "notes": "Only INTEREST component qualifies (not principal). Loan must be from approved institution.",
        "category": "Chapter VI-A",
    },
    {
        "section": "80EE",
        "name": "Home Loan Interest (First-Time Buyer, 2016-17)",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": 50000,
        "limit_text": "₹50,000 per year (over and above Sec 24(b) ₹2L limit)",
        "instruments": ["Interest on housing loan sanctioned between 01-Apr-2016 and 31-Mar-2017"],
        "notes": "Loan ≤ ₹35L; property value ≤ ₹50L. Not available if 80EEA is claimed.",
        "category": "Chapter VI-A",
    },
    {
        "section": "80EEA",
        "name": "Home Loan Interest (Affordable Housing, 2019-22)",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": 150000,
        "limit_text": "₹1,50,000 per year (over and above Sec 24(b) ₹2L limit)",
        "instruments": ["Interest on housing loan sanctioned between 01-Apr-2019 and 31-Mar-2022"],
        "notes": "Stamp duty value ≤ ₹45L. First-time buyer only. Cannot claim 80EE simultaneously.",
        "category": "Chapter VI-A",
    },
    {
        "section": "80EEB",
        "name": "Electric Vehicle Loan Interest",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": 150000,
        "limit_text": "₹1,50,000 per year",
        "instruments": ["Interest on loan for purchase of electric vehicle (sanctioned 01-Apr-2019 to 31-Mar-2023)"],
        "notes": "Loan from bank/NBFC. For personal or business use EV.",
        "category": "Chapter VI-A",
    },
    {
        "section": "80G",
        "name": "Donations to Charitable Organisations",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": None,
        "limit_text": "100% or 50% deduction (with or without 10% qualifying limit)",
        "instruments": [
            "PM National Relief Fund — 100% no limit",
            "PM CARES Fund — 100% no limit",
            "Chief Minister's Relief Fund — 100% no limit",
            "Approved charitable institutions — 50%, subject to 10% of adjusted GTI",
        ],
        "notes": "Get 80G certificate from the institution. No cash donations above ₹2,000.",
        "category": "Chapter VI-A",
    },
    {
        "section": "80GG",
        "name": "Rent Paid (No HRA in Salary)",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": 60000,
        "limit_text": "Least of: (i) ₹5,000/month (₹60,000/year), (ii) 25% of total income, (iii) Rent paid − 10% of total income",
        "instruments": ["Rent paid for residential accommodation (when no HRA component in salary)"],
        "notes": "Employee or spouse should NOT own a house. Cannot claim HRA and 80GG simultaneously.",
        "category": "Chapter VI-A",
    },
    {
        "section": "80TTA",
        "name": "Savings Bank Interest",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": 10000,
        "limit_text": "₹10,000 per year",
        "instruments": ["Interest from savings bank account (bank, co-operative, post office)"],
        "notes": "Only savings account interest (NOT FD / RD). Senior citizens should use 80TTB instead.",
        "category": "Chapter VI-A",
    },
    {
        "section": "80TTB",
        "name": "Senior Citizens Interest Income",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": 50000,
        "limit_text": "₹50,000 per year (SENIOR CITIZENS ONLY — 60+ years)",
        "instruments": [
            "Interest from savings bank account",
            "Interest from fixed deposits",
            "Interest from recurring deposits",
            "Interest from post office deposits",
        ],
        "notes": "Senior citizens should claim 80TTB (₹50K) instead of 80TTA (₹10K). Cannot claim both.",
        "category": "Chapter VI-A",
    },
    {
        "section": "80U",
        "name": "Self Disability",
        "old_regime": True,
        "new_regime": False,
        "limit_amount": 125000,
        "limit_text": "₹75,000 (disability 40%+) or ₹1,25,000 (severe disability 80%+)",
        "instruments": ["Fixed deduction for certified disabled individuals (regardless of actual expenses)"],
        "notes": "Requires medical certificate. Covers visual, hearing, locomotor, mental disabilities.",
        "category": "Chapter VI-A",
    },
]

# ── House Property Deductions ──────────────────────────────────────────────────

HOUSE_PROPERTY_DEDUCTIONS: List[Dict[str, Any]] = [
    {
        "section": "Sec 24(a)",
        "name": "Standard Deduction on House Property",
        "old_regime": True,
        "new_regime": False,
        "limit_text": "30% of Net Annual Value (auto-computed)",
        "notes": "Only for let-out property. Not applicable for self-occupied.",
        "category": "House Property",
    },
    {
        "section": "Sec 24(b)",
        "name": "Home Loan Interest — Self-Occupied",
        "old_regime": True,
        "new_regime": False,
        "limit_text": "Up to ₹2,00,000 per year (pre-construction interest deductible in 5 equal instalments)",
        "notes": "Loan must be for purchase/construction (not repair). Property must be self-occupied.",
        "category": "House Property",
    },
    {
        "section": "Sec 24(b)",
        "name": "Home Loan Interest — Let-Out Property",
        "old_regime": True,
        "new_regime": False,
        "limit_text": "No upper limit. Actual interest paid (loss set-off against salary capped at ₹2L)",
        "notes": "Loss from let-out property beyond ₹2L can be carried forward for 8 years.",
        "category": "House Property",
    },
]

# ── New Tax Regime — What IS Available ───────────────────────────────────────

NEW_REGIME_AVAILABLE: List[Dict[str, Any]] = [
    {
        "section": "Standard Deduction",
        "name": "Standard Deduction from Salary",
        "limit_text": "₹75,000 per year (increased from ₹50,000 in Budget 2023)",
        "notes": "Automatically applied. No documentation required.",
    },
    {
        "section": "80CCD(2)",
        "name": "Employer's NPS Contribution",
        "limit_text": "14% of salary (Govt) / 10% of salary (Private). No monetary cap.",
        "notes": "Available in NEW regime. Highly beneficial — tax-free employer contribution.",
    },
    {
        "section": "80CCH",
        "name": "Agnipath Scheme (Agniveer Corpus)",
        "limit_text": "Full amount deposited in Agniveer Corpus Fund",
        "notes": "Only for Armed Forces Agniveer personnel.",
    },
    {
        "section": "Sec 10(10)",
        "name": "Gratuity",
        "limit_text": "Up to ₹20,00,000",
        "notes": "Still exempt in the new regime.",
    },
    {
        "section": "Sec 10(10AA)",
        "name": "Leave Encashment on Retirement",
        "limit_text": "Up to ₹25,00,000 for non-govt; fully exempt for Govt.",
        "notes": "Still exempt in the new regime.",
    },
    {
        "section": "Sec 10(14)",
        "name": "Transport Allowance (Disabled)",
        "limit_text": "₹3,200 per month",
        "notes": "Only for physically disabled employees.",
    },
    {
        "section": "Sec 10(10C)",
        "name": "VRS Compensation",
        "limit_text": "Up to ₹5,00,000",
        "notes": "Voluntary Retirement Scheme benefit still exempt.",
    },
    {
        "section": "Rebate 87A",
        "name": "Tax Rebate u/s 87A",
        "limit_text": "Up to ₹60,000 rebate if taxable income ≤ ₹12,00,000 (effective zero tax up to ₹12,75,000 after standard deduction)",
        "notes": "Budget 2025 enhanced rebate — biggest advantage of the new regime for income ≤ ₹12.75L.",
    },
]

# ── Tax Slab Reference ────────────────────────────────────────────────────────

NEW_REGIME_SLABS_INFO = {
    "title": "New Tax Regime — Tax Slabs (AY 2026-27 / FY 2025-26 onwards)",
    "applicable_from": "FY 2025-26",
    "slabs": [
        {"range": "₹0 – ₹4,00,000", "rate": "NIL", "notes": ""},
        {"range": "₹4,00,001 – ₹8,00,000", "rate": "5%", "notes": ""},
        {"range": "₹8,00,001 – ₹12,00,000", "rate": "10%", "notes": ""},
        {"range": "₹12,00,001 – ₹16,00,000", "rate": "15%", "notes": ""},
        {"range": "₹16,00,001 – ₹20,00,000", "rate": "20%", "notes": ""},
        {"range": "₹20,00,001 – ₹24,00,000", "rate": "25%", "notes": ""},
        {"range": "Above ₹24,00,000", "rate": "30%", "notes": ""},
    ],
    "effective_zero_tax": "Income up to ₹12,75,000 (₹12L + ₹75K standard deduction) — NIL tax via 87A rebate",
}

OLD_REGIME_SLABS_INFO = {
    "title": "Old Tax Regime — Tax Slabs",
    "applicable_from": "Unchanged since FY 2017-18",
    "under_60": [
        {"range": "₹0 – ₹2,50,000", "rate": "NIL", "notes": ""},
        {"range": "₹2,50,001 – ₹5,00,000", "rate": "5%", "notes": ""},
        {"range": "₹5,00,001 – ₹10,00,000", "rate": "20%", "notes": ""},
        {"range": "Above ₹10,00,000", "rate": "30%", "notes": ""},
    ],
    "senior_60_80": [
        {"range": "₹0 – ₹3,00,000", "rate": "NIL", "notes": ""},
        {"range": "₹3,00,001 – ₹5,00,000", "rate": "5%", "notes": ""},
        {"range": "₹5,00,001 – ₹10,00,000", "rate": "20%", "notes": ""},
        {"range": "Above ₹10,00,000", "rate": "30%", "notes": ""},
    ],
    "super_senior_80_plus": [
        {"range": "₹0 – ₹5,00,000", "rate": "NIL", "notes": ""},
        {"range": "₹5,00,001 – ₹10,00,000", "rate": "20%", "notes": ""},
        {"range": "Above ₹10,00,000", "rate": "30%", "notes": ""},
    ],
    "rebate_87a": "₹12,500 rebate if taxable income ≤ ₹5,00,000",
}

SURCHARGE_INFO = [
    {"income_range": "₹50L – ₹1Cr", "old_regime": "10%", "new_regime": "10%"},
    {"income_range": "₹1Cr – ₹2Cr", "old_regime": "15%", "new_regime": "15%"},
    {"income_range": "₹2Cr – ₹5Cr", "old_regime": "25%", "new_regime": "25%"},
    {"income_range": "Above ₹5Cr", "old_regime": "37%", "new_regime": "25% (capped)"},
]

CESS_INFO = "Health and Education Cess: 4% on (Income Tax + Surcharge)"
